### ISSUE TITLE
Add to contributors

### ISSUE THREAD

**Issue by evanplaice** [typeiii/csv#4]
@coltonehrman Add yourself to the contributors list and -- if you want -- the license.

BTW, package.json only allows one author/project so I added myself as a contributor instead.

**Comment by coltonehrman** [comment]
Done

**Comment by evanplaice** [comment]
FYI, you *should* be able to push directly to this repo. If not, let me know.

**Comment by evanplaice** [comment]
Feel free to push little stuff directly. I'd like to stick to a Feature Workflow (ie branch+pr) for features tho.

**Comment by coltonehrman** [comment]
Yes, I was able to directly modify and commit from GitHub, I figured with the contributors change that would suffice and will use the conventional branch+pr workflow for other things

**Comment by evanplaice** [comment]
Cool. This is where the fun part begins.
